### ISSUE TITLE
utils

### ISSUE THREAD

**Issue by user2020psk** [HITsz-TMG/PPAT#3]
您好，打扰一下您，请问您是不是少长传了utils文件夹

**Comment by twinkle121** [comment]
请问您复现出来了吗

**Comment by foggy-frost-forest** [comment]
多谢提醒, 确实遗漏了, 现已上传, 感谢对我们工作的关注!

**Comment by user2020psk** [comment]
他上传utils了，请问您复现出来了吗


Monkey
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HITsz-TMG/PPAT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月29日(星期天) 晚上7:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HITsz-TMG/PPAT] utils (Issue #3)





 
请问您复现出来了吗

**Comment by user2020psk** [comment]
感谢上传代码，请问一下您这个代码是用cpu跑的吗，用gpu可行吗？


Monkey
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HITsz-TMG/PPAT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月30日(星期一) 晚上8:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HITsz-TMG/PPAT] utils (Issue #3)





 
多谢提醒, 确实遗漏了, 现已上传, 感谢对我们工作的关注!

**Comment by foggy-frost-forest** [comment]
你好, 可以用GPU跑, 只需要在运行命令中添加"--device {GPU id}", 例如--device 3

**Comment by user2020psk** [comment]
好嘞，感谢您的解答。代码中的cpu字符串是不是要替换成gpu。




Monkey
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HITsz-TMG/PPAT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月3日(星期五) 下午3:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HITsz-TMG/PPAT] utils (Issue #3)





 
你好, 可以用GPU跑, 只需要在运行命令中添加"--device {GPU id}", 例如--device 3

**Comment by foggy-frost-forest** [comment]
目前的代码应该可以直接在GPU上运行; 对于BERT的代码, --device -1是使用CPU, --device 0是使用0号卡(至少需要40G显存), 对于Longfomer的代码, 可以通过--encoder_device将encoder和reasoning module放在两张卡上, 防止OOM大; 如果您还有其他问题, 欢迎提问
