### ISSUE TITLE
about experiment details

### ISSUE THREAD

**Issue by lyj963** [HITsz-TMG/PPAT#7]
您好，非常感谢您的工作及开源的代码，想请问一下您的相关实验设置的一些细节：
1、数据集EventStoryLine中因果标签PRECONDITION和FALLING ACTION根据数据集相关论文描述是带有方向的，在MAVEN-ERE论文的代码中对ESL数据的处理也是将PRECONDITION和FALLING ACTION作为两个标签处理的且有方向，但是您的代码中将两个标签同视作一种因果标签并且不带方向，请问这是沿用了之前哪篇工作的实验设置（因为您之前大部分工作没有开源代码或者没有数据集处理的部分，非常感谢您能给出完整代码）。
2、请问您在论文中进行的MAVEN-ERE数据集的实验具体采用的怎样的实验设置，因为MAVEN-ERE中的CAUSE和PRECONDITION两种因果标签也是带有方向性的，请问您是与主实验类似都看作一种无方向的因果关系，还是与MAVEN-ERE代码中一样进行{CAUSE，PRECONDITION，NONE}的三分类模式？
如您方便的话可以通过github issue或者邮箱lliyingjie@iie.ac.cn回复，再次感谢您的工作！

**Comment by foggy-frost-forest** [comment]
您好，感谢您对我们工作的关注！
1. 忽略数据集的因果方向是沿用了之前的RichGCN和ERGO的实验设置
2. 是的, 为了保持实验的一致性, 我们也忽略了MAVEN-ERE的因果方向, 其代码和其他的数据集一样, 只需要修改数据路径和相关超参数（详见论文的实验设置，和EventStoryLine基本一致）
3. 是的, 目前开源的是超参数和我们论文汇报的一致

**Comment by lyj963** [comment]
非常感谢您的回复！

**Comment by Catworkdog** [comment]
为什么会忽略了方向，这会不会导致因果传递时出现方向传递的错误，期望您的回复，非常感谢

**Comment by foggy-frost-forest** [comment]
您好, 感谢您的提问

忽略因果方向是因为我们沿用了之前的工作(RichGCN和ERGO)的实验设置, 由此能够和他们的方法公平的比较。
您可以通过修改代码的建图方式，将现有的双向图改成单向图，从而防止因果方向传播错误。
